lab3/project/jdmcars/cars/api/urls.py
from rest_framework import routers

from django.urls import path, include

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'marks', views.MarkViewSet)
router.register(r'models', views.ModelViewSet)
router.register(r'userprofiles', views.UserProfileViewSet)
router.register(r'offers', views.OfferViewSet)
router.register(r'statistics', views.StatisticsViewSet)

urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += router.urls

lab3/project/jdmcars/cars/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic.base import RedirectView
from jdmcars import settings

from . import views
from . import forms

app_name = 'cars'
urlpatterns = [
    path('offers/<str:mark>/<str:model>/<int:pk>/', views.OfferDetails.as_view(), name='offer-details'),
    path('offers/<str:mark>/<str:model>/', views.ModelsView.as_view(), name='models'),
    path('offers/<str:mark>', views.MarksView.as_view(), name='marks'),
    path('offers/', views.OffersView.as_view(), name='offers'),
    path('profile/selfoffers/edit/<int:pk>', views.EditOfferView.as_view(), name='edit-offer'),
    path('profile/selfoffers/delete/<int:pk>', views.DeleteOfferView.as_view(), name='delete'),
    path('profile/selfoffers/addfavorite/<int:pk>', views.AddFavoriteView.as_view(), name='add-favorite'),
    path('profile/selfoffers/addoffer/', views.AddOfferView.as_view(), name='add-offer'),
    path('profile/selfoffers/', views.SelfOffersView.as_view(), name='self-offers'),
    path('profile/favoriteoffers/', views.FavoriteOffersView.as_view(), name='favorite-offers'),
    path('profile/', views.EditProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('', views.IndexView.as_view(), name='index'),
]

lab3/project/jdmcars/jdmcars/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('cars.api.urls'), name='api'),
    path('', include('cars.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab3/project/jdmcars/cars/models.py
from django.db import models
from django.urls import reverse

from .db_models.offer import Offer
from .db_models.statistics import Statistics
from .db_models.userprofile import UserProfile
from .db_models.model import Model
from .db_models.mark import Mark

lab3/project/jdmcars/cars/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms.models import fields_for_model
from django.forms.widgets import EmailInput
from django.shortcuts import render

from .models import *

from .logger import logger

class SignInForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['username', 'password']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['password'].label = 'Password'

    def clean(self):
        logger.info('Validating users authenticating')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            logger.error(f'User {username} not found')
            raise forms.ValidationError(f'User {username} not found')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                logger.error(f'Incorrect password for username "{username}"')
                raise forms.ValidationError('Incorrect password')
            else:
                logger.info(f"User {str(user)} can be authenticated")
        return self.cleaned_data



class SignUpForm(forms.ModelForm):

    email = forms.EmailField(widget=EmailInput, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['email'].label = 'Email'
        self.fields['password'].label = 'Password'
        self.fields['confirm_password'].label = 'Confirm Password'



    def clean_username(self):
        logger.info('Validating username to sign up a User')
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            logger.error(f"User with uesrname {username} already exists")
            raise forms.ValidationError(f'User with username "{username}" already exists')
        return username

    def clean(self):
        logger.info('Confirming password to sign up a user')
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            logger.error('Passwords do not match')
            raise forms.ValidationError('Passwords do not match')
        return self.cleaned_data

    class Meta:
        
        model = User
        fields = ['username', 'email', 'password', 'confirm_password']


class AddOfferForm(forms.ModelForm):

    class Meta:   
        model = Offer
        fields = fields_for_model(model)
        exclude = ['owner', 'statistics']


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ['favorite_offers', 'user']

class EditOfferForm(forms.ModelForm):

    class Meta:
        model = Offer
        exclude = ['owner', 'statistics']

lab3/project/jdmcars/cars/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser, IsAuthenticated

from .serializers import *
from ..models import *

class UserViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAdminUser]

    queryset = User.objects.all()
    serializer_class = UserSerializer

class MarkViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAuthenticated]

    queryset = Mark.objects.all()
    serializer_class = MarkSerializer

class ModelViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAuthenticated]

    queryset = Model.objects.all()
    serializer_class = ModelSerializer

class UserProfileViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAdminUser]

    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer

class OfferViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAuthenticated]

    queryset = Offer.objects.all()
    serializer_class = OfferSerializer

class StatisticsViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAuthenticated]

    queryset = Statistics.objects.all()
    serializer_class = StatisticsSerializer

lab3/project/jdmcars/cars/views.py
from django import forms
from django.contrib.auth import authenticate, login
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.views.generic import View
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from datetime import datetime

from .forms import EditProfileForm, SignInForm, SignUpForm, AddOfferForm, EditOfferForm
from .models import *

from .logger import logger

import threading

class EmailThread(threading.Thread):

    def __init__(self, email : EmailMessage):
        self.email = email
        threading.Thread.__init__(self)

    def run(self):
        logger.info('Async email sending')
        self.email.send(fail_silently=False)

def get_last_objects(model:object, order_by:str, count:int):
    logger.debug('Test message')
    try:
        logger.info(f'Get objects of {str(model)}')
        return model.objects.order_by(order_by)[:count]
    except Exception:
        logger.error(f'Cannot get objects of {str(model)}')
        return None

class IndexView(generic.ListView):

    template_name = 'cars/index.html'
    context_object_name = 'latest_offers_list'

    def get_queryset(self):
        """Return the last five added cars."""
        return get_last_objects(Offer, '-mark', 8)

class OfferDetails(generic.DetailView):

    def get(self, request, mark, model, pk, *args, **kwargs):
        offer = get_object_or_404(Offer, pk=pk)
        logger.info(f'Get details of offer {str(offer)}')
        offer.statistics.total_views += 1
        offer.statistics.todays_views += 1
        offer.statistics.save()
        context = {
            'offer' : offer
        }
        return render(request, 'cars/offerdetails.html', context)

class OffersView(generic.ListView):

    def get(self, request, *args, **kwargs):
        favorite_offers = None
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                related_user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get offers for {str(related_user)}')
                favorite_offers = related_user.favorite_offers.filter(userprofile=related_user)
        else:
            logger.info(f'Get offers for Anonymous')
        context = {
            'offers' : Offer.objects.all(),
            'favorite_offers' : favorite_offers
        }
        return render(request, 'cars/offers.html', context)


class MarksView(generic.ListView):

    def get(self, request, mark, *args, **kwargs):
        favorite_offers = None
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                related_user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get offers of mark {str(mark)} for {str(related_user)}')
                favorite_offers = related_user.favorite_offers.filter(userprofile=related_user)
        else:
            logger.info(f'Get offers of {str(mark)} for Anonymous')
        related_mark = get_object_or_404(Mark, mark=mark)
        offers_of_mark = get_list_or_404(Offer, mark=related_mark.pk)
        context = {
            'offers' : offers_of_mark,
            'favorite_offers' : favorite_offers,
            'mark' : mark
        }
        return render(request, 'cars/mark.html', context)


class ModelsView(generic.ListView):

    def get(self, request, mark, model, *args, **kwargs):
        favorite_offers = None
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                related_user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get offers of model {str(model)} for {str(related_user)}')
                favorite_offers = related_user.favorite_offers.filter(userprofile=related_user)
        else:
            logger.info(f'Get offers of model {str(model)} for Anonymous')
        related_mark = get_object_or_404(Mark, mark=mark)
        related_model = get_object_or_404(Model, model=model)
        offers_of_model = get_list_or_404(Offer, model=related_model.pk, mark=related_mark.pk)
        context = {
            'offers' : offers_of_model,
            'favorite_offers' : favorite_offers,
            'mark' : mark,
            'model' : model
        }
        return render(request, 'cars/model.html', context)


class FavoriteOffersView(generic.ListView):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                related_user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get favorite offers for {str(related_user)}')
                favorite_offers = related_user.favorite_offers.filter(userprofile=related_user)
                context = {
                    'offers' : favorite_offers,
                }
                return render(request, 'cars/favoriteoffers.html', context)
            else:
                return render(request, 'cars/favoriteoffers.html')
        else:
            logger.warning('User not authorised to visit favorite objects')
            return HttpResponseRedirect('signin/')


class SelfOffersView(generic.ListView):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                related_user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get self offers for {str(related_user)}')
                user_offers = Offer.objects.filter(owner=related_user)
                context = {
                    'offers' : user_offers,
                }
                return render(request, 'cars/selfoffers.html', context)
            else:
                return render(request, 'cars/selfoffers.html')
        else:
            logger.warning('User not authorised to visit self offers')
            return HttpResponseRedirect('signin/')


class DeleteOfferView(View):

    def get(self, request, pk):
        if request.user.is_authenticated:
            redirect_to = request.GET.get('next', '')
            if not request.user.is_superuser:
                offer = Offer.objects.get(pk=pk)
                logger.info(f'User {str(request.user)} deleted offer {str(offer)}')
                offer.delete()
            return HttpResponseRedirect(redirect_to)
        else:
            logger.warning('User not authorised to delete offer')
            return HttpResponseRedirect('signin/')

class AddFavoriteView(View):

    def get(self, request, pk):
        if request.user.is_authenticated:
            redirect_to = request.GET.get('next', '')
            if not request.user.is_superuser:
                offer = Offer.objects.get(pk=pk)
                related_user = get_object_or_404(UserProfile, user=request.user)
                if not offer in related_user.favorite_offers.all():
                    logger.info(f'User {str(related_user)} added to favorites offer {str(offer)}')
                    related_user.favorite_offers.add(offer)
                else:
                    logger.info(f'User {str(related_user)} removed from favorites offer {str(offer)}')
                    related_user.favorite_offers.remove(offer)
            return HttpResponseRedirect(redirect_to)
        else:
            logger.warning('User not authorised to add offer to favorites')
            return HttpResponseRedirect('signin/')


class UserProfileView(View):
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not request.user.is_superuser:
                user = UserProfile.objects.get(user=request.user)
                logger.info(f'Get info of user {str(request.user)}')
                context = {
                    'user' : user,
                }
                return render(request, 'cars/profile.html', context)
            else:
                return render(request, 'cars/profile.html') 
        else:
            logger.warning('User not authorised to get info of user')
            return HttpResponseRedirect('signin/')


class SignInView(View):

    def get(self, request, *args, **kwargs):
        logger.info('Signing in')
        form = SignInForm(request.POST or None)
        context = {'form':form,}
        return render(request, 'cars/signin.html', context)

    def post(self, request, *args, **kwargs):
        logger.info('POST data to authorise user')
        redirect_to = request.GET.get('next', '')
        form = SignInForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                logger.info(f'Authorised user {str(user)}')
                return HttpResponseRedirect(redirect_to)
        logger.warning('bad POST data to authorise user')
        context = {'form' : form, 'offers' : get_list_or_404(Offer)}
        return render(request, 'cars/signin.html', context)


class SignUpView(View):

    def get(self, request, *args, **kwargs):
        logger.info('Signing up')
        form = SignUpForm(request.POST or None)
        context = {'form':form, }
        return render(request, 'cars/signup.html', context)

    def post(self, request, *args, **kwargs):
        logger.info('POST data to sign up user')
        redirect_to = request.GET.get('next', '')
        form = SignUpForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data['username']
            new_user.save()
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            user_email = form.cleaned_data['email']

lab3/project/jdmcars/cars/templates/cars/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>JDM Cars Sales</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    {% block styles %}
    {% endblock styles %}
  </head>
  <body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container px-5">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="navbar-brand" href="{% url 'cars:index' %}">JDM Cars</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </button>
    </li>
      <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'cars:offers' %}">Offers</a></li>      
        </ul>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:profile' %}?next={{request.path}}">{{ request.user }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:self-offers' %}">My Offers</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:favorite-offers' %}">Favorite Offers</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:logout' %}?">Log Out</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:signin' %}?next={{request.path}}">Sign In</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cars:signup' %}?next={% url 'cars:profile' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
      {% block breadcrumbs %}
      {% endblock breadcrumbs %}
      {% block content %}
      <!-- Heading Row-->
      <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
          <img
            class="img-fluid rounded mb-4 mb-lg-0"
            src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg"
            alt="..."
          />
        </div>
        <div class="col-lg-5">
          <h1 class="font-weight-light">Business Name or Tagline</h1>
          <p>
            This is a template that is great for small businesses. It doesn't
            have too much fancy flare to it, but it makes a great use of the
            standard Bootstrap core components. Feel free to use this template
            for any project you want!
          </p>
          <a class="btn btn-primary" href="#!">Call to Action!</a>
        </div>
      </div>
      <!-- Call to Action-->
      <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body">
          <p class="text-white m-0">
            This call to action card is a great place to showcase some important
            information or display a clever tagline!
          </p>
        </div>
      </div>
      <!-- Content Row-->
      <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
          <div class="card h-100">
            <div class="card-body">
              <h2 class="card-title">Card One</h2>
              <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem
                magni quas ex numquam, maxime minus quam molestias corporis
                quod, ea minima accusamus.
              </p>
            </div>
            <div class="card-footer">
              <a class="btn btn-primary btn-sm" href="#!">More Info</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-5">
          <div class="card h-100">
            <div class="card-body">
              <h2 class="card-title">Card Two</h2>
              <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod
                tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem
                sunt quam eaque, vel, non in id dolore voluptates quos eligendi
                labore.
              </p>
            </div>
            <div class="card-footer">
              <a class="btn btn-primary btn-sm" href="#!">More Info</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-5">
          <div class="card h-100">
            <div class="card-body">
              <h2 class="card-title">Card Three</h2>
              <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem
                magni quas ex numquam, maxime minus quam molestias corporis
                quod, ea minima accusamus.
              </p>
            </div>
            <div class="card-footer">
              <a class="btn btn-primary btn-sm" href="#!">More Info</a>
            </div>
          </div>
        </div>
      </div>
      {% endblock content %}
    </div>
    <!-- Footer-->
    {% block footer %}
    <footer class="py-5 bg-dark">
      <div class="container px-4 px-lg-5">
        <div class="m-0 text-center text-white">
          Copyright &copy; JDM Cars 2021
        </div>
      </div>
    </footer>
    {% endblock footer %}
    <!-- Bootstrap core JS-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
      integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

lab3/project/jdmcars/cars/templates/cars/mark.html
{% extends "cars/offers.html" %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'cars:offers' %}">Cars</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ mark }}</a></li>
    </ol>
</nav>
{% endblock %}

lab3/project/jdmcars/cars/templates/cars/model.html
{% extends "cars/offers.html" %} 

{% block breadcrumbs %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'cars:offers' %}">Cars</a></li>
        <li class="breadcrumb-item"><a href="{% url 'cars:marks' mark %}">{{ mark }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ model }}</a></li>
    </ol>
</nav>
{% endblock %}

lab3/project/jdmcars/cars/templates/cars/profile.html
{% extends "cars/base.html" %}

{% block content %}
{{ user }}
{% endblock %}

lab3/project/jdmcars/cars/templates/cars/selfoffers.html
{% extends "cars/base.html" %} 
{% block styles %}
<style>
  .item-title {
    margin: -2px 0 12px;
    font-family: "Montserrat", system-ui, sans-serif;
    font-size: 18px;
    font-weight: 800;
    line-height: 22px;
  }

  .item {
    position: relative;
    padding: 20px;
    border-top: 1px solid #f0f4f8;
  }

  .item-photo {
    position: relative;
    box-sizing: border-box;
    align-self: flex-start;
    width: 200px;
  }

  .item-about {
    display: flex;
    flex-direction: column;
    width: 202px;
    padding-left: 20px;
    padding-right: 20px;
  }

  .item-info {
    display: flex;
    flex-wrap: wrap;
    margin-bottom: -2px;
    font-size: 13px;
  }

  .item-info-date {
    color: #777d82;
    white-space: nowrap;
  }

  .item-info-location {
    margin-right: 8px;
    font-weight: 600;
    white-space: nowrap;
  }

  .item-params {
    width: 202px;
    margin-top: -2px;
    padding-right: 20px;
    font-size: 15px;
    line-height: 22px;
  }

  .item-price {
    flex: 1;
    display: flex;
    flex-direction: column;
    margin-top: -2px;
    text-align: center;
  }

  .item-controls {
    position: absolute;
    top: -7px;
    right: -5px;
    display: flex;
  }

  .item-wrap {
    position: relative;
    display: flex;
  }

  ul {
    list-style-type: none;
}
</style>
{% endblock %} 
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <h1 class="nav-item">Your Offers</h1>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a href="{% url 'cars:add-offer' %}?next={{request.path}}">
                <button class="btn btn-primary" id="sidebarToggle">Add Offer</button>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                </a>
              </li>
          </ul>
      </div>
  </div>
</nav>
{% if offers %}
<ul class="list-group">
  {% for offer in offers %}
  <li class="item">
    <div class="item-wrap">
      <div class="item-photo">
        <a href="{% url 'cars:offer-details' offer.mark offer.model offer.pk %}">
        <img
          src="{{ offer.image.url }}"
          class="img-fluid"
          width="200"
          height="150"
          alt="{{ offer }}"
        />
        </a>
      </div>
      <div class="item-about">
        <h3 class="item-title" line>
          <a href="{% url 'cars:offer-details' offer.mark offer.model offer.pk %}">
            <span class="link-text">
              {{ offer.mark }} {{ offer.model }} {{ offer.yaer }}
            </span>
          </a>
        </h3>
        <div class="item-info">
          <div class="item-info-location">{{ offer.owner.address }}</div>
          <div class="item-info-date">{{ offer.statistics.publish_date }}</div>
        </div>
      </div>
      <div class="item-params">
        <div>{{ offer.year }}</div>
        <div>
          Today viewed: {{ offer.statistics.todays_views }}
        </div>
        <div>
          <span>Total viewed: {{ offer.statistics.total_views }}</span>
        </div>
      </div>
      <div class="item-price">
        <div>{{ offer.price }}$</div>
      </div>
      <div class="item-controls">
        <a class="btn btn-primary" href="{% url 'cars:edit-offer' offer.pk %}?next={{request.path}}">Edit</a>
        <a class="btn btn-danger" href="{% url 'cars:delete' offer.pk %}?next={{request.path}}">Delete</a>
      </div>
    </div>
  </li>
  {% endfor %}
</ul>
{% else %}
<div class="col-md-12" style="margin-top: 30px;">
    <h3>Seems like you hasn't added any offers</h3>
  </div>
{% endif %}
{% endblock %}